### ISSUE TITLE
mountedInstances.instance.bind is not a function

### ISSUE THREAD

**Issue by radicalpi** [CanopyTax/single-spa-vue#3]
When running v1.0.0 with the included PR #2 and single-spa@3.7.0, the following error is thrown:
`Uncaught TypeError: 'appname' died in status NOT_MOUNTED: mountedInstances.instance.bind is not a function` 

The child Vue instance is still mounted and functions as expected despite the error. Removing this line and reverting to pre-v1.0.0 behavior eliminates this error.

**Comment by joeldenning** [comment]
Dang, I should have tested that code more thoroughly before merging and publishing. I am on vacation right now, but will take a look at this in a couple days. For those experiencing this issue, you can try using single-spa-vue@0.0.3 (instead of single-spa-vue@1.0.0)

**Comment by joeldenning** [comment]
Good news -- I found a bit of time and it didn't take too long to fix this. I have published single-spa-vue@1.0.1 which fixes this issue. My guess is that @ghulamMustafaRaza is using a different (maybe older) version of vue that returns a function instead of an object when [calling new Vue()](https://github.com/CanopyTax/single-spa-vue/blob/master/src/single-spa-vue.js#L42). I have updated the code to be defensive and so it will hopefully work in both situations.

@ghulamMustafaRaza what version of vue did you use when you reported #1 ?

**Comment by ghulamMustafaRaza** [comment]
I'm using vue@^2.5.13

**Comment by ghulamMustafaRaza** [comment]
I'm using vue@^2.5.13

**Comment by ghulamMustafaRaza** [comment]
I'm using vue@^2.5.13

**Comment by joeldenning** [comment]
Interesting -- I am using vue@2.5.13 as well and the [returned instance](https://github.com/CanopyTax/single-spa-vue/blob/master/src/single-spa-vue.js#L42) is not a function (and so you can't call `.bind()` on it).

Can you confirm if the `instance` object returned to you is a function? Also can you confirm if things still work for you with single-spa-vue@1.0.1?
